### ISSUE TITLE
Include descriptive location included in the json

### ISSUE THREAD

**Issue by joelmbell** [Vegas-iOS-Developers/LasVegasArtWorkTour#8]
There is a field called "location" sent back in the json and its a descriptive version of the the location like "Firefighters Park" and "Stuck Community Center Lobby". We're currently not parsing it into the Artwork Model. I think this could be really useful information in the app to help people find exactly what piece of art we're talking about.

**Comment by WilliamJones** [comment]
I totally agree. I did not notice the location information details until after I developed the model. We can totally expand the model or the UI to use this additional information.

**Comment by joelmbell** [comment]
Resolved with commit 94397a8
